### ISSUE TITLE
Next.js + react-json-to-table not playing nice

### ISSUE THREAD

**Issue by MariuzM** [thehyve/react-json-to-table#19]
getting this error in Next.js
```
error - ./node_modules/react-json-to-table/build/lib/components/JsonToTable/JsonToTable.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/react-json-to-table/build/lib/components/JsonToTable/JsonToTable.js
```

**Comment by solangeDev** [comment]
I have this error with next js 
node_modules/react-json-to-table/build/lib/components/JsonToTable/JsonToTable.css:1
.json-to-table td,
^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)

**Comment by paul-asvb** [comment]
+1
